name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # with this, even if the job fail, the other jobs won't stop and it will be mark as success
    strategy: 
      matrix: 
        node-version: [12.x, 14.x, 16.x]
        operating-system: [ubuntu-latest, windows-latest]
        include: # standalone combinations
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: 
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
